### ISSUE TITLE
Fix Google Places Image Integration - Events/Places Not Showing Images

### ISSUE THREAD

**Issue by ChrisBaptiste** [ChrisBaptiste/Budget-BackPack-FullStack-React-App#4]
## Issue Description

Fix the Google Places API integration to display images for events and places in search results. Currently, the app successfully retrieves Google Places data but **images are not displaying**, creating a poor user experience. This is **Priority P0 - Critical for user experience**.

## Current State Analysis

**? What's Working:**
- Google Places API integration is functional
- Place data retrieval works correctly
- Search results show text-based information

**? What's Missing:**
- No image display functionality
- No Google Places Photo API integration
- No image carousel/gallery component
- Missing fallback images for places without photos

#### 1. Google Places Photo API Integration
```javascript
// Add to existing search routes (routes/searchRoutes.js)
const getPlacePhotos = async (photoReference, maxWidth = 400) => {
  try {
    const photoUrl = `https://maps.googleapis.com/maps/api/place/photo?maxwidth=${maxWidth}&photoreference=${photoReference}&key=${process.env.GOOGLE_PLACES_API_KEY}`;
    return photoUrl;
  } catch (error) {
    console.error('Error fetching place photo:', error);
    return null;
  }
};

// Update places search to include photo URLs
const enrichPlacesWithPhotos = async (places) => {
  return Promise.all(places.map(async (place) => {
    if (place.photos && place.photos.length > 0) {
      const photoUrls = await Promise.all(
        place.photos.slice(0, 3).map(photo => 
          getPlacePhotos(photo.photo_reference)
        )
      );
      place.photoUrls = photoUrls.filter(url => url !== null);
    } else {
      place.photoUrls = [];
    }
    return place;
  }));
};
```

#### 2. Image Proxy/CDN Setup
```javascript
// middleware/imageProxy.js
const createImageProxy = (req, res, next) => {
  // Proxy Google Places images through our server to handle CORS
  // Add image optimization and caching
};
```

#### 3. Updated API Response Format
```javascript
// Enhanced response format for events/places
{
  id: "place_id",
  name: "Place Name",
  description: "Place description",
  rating: 4.5,
  price_level: 2,
  photos: [
    {
      photo_reference: "reference_string",
      width: 400,
      height: 300
    }
  ],
  photoUrls: [
    "https://your-api.com/proxy/image/url1",
    "https://your-api.com/proxy/image/url2",
    "https://your-api.com/proxy/image/url3"
  ],
  fallbackImage: "/images/default-place.jpg"
}
```

#### 1. New Image Gallery Component
```javascript
// components/Search/ImageGallery.jsx
import React, { useState } from 'react';

const ImageGallery = ({ images, placeName }) => {
  const [currentImage, setCurrentImage] = useState(0);
  const [imageError, setImageError] = useState(false);

  const handleImageError = () => {
    setImageError(true);
  };

  const fallbackImage = '/images/default-place.jpg';

  if (!images || images.length === 0 || imageError) {
    return (
      <img 
        src={fallbackImage} 
        alt={`${placeName} - Default`}
        className="search-result-image fallback"
        loading="lazy"
      />
    );
  }

  return (
    <div className="image-gallery">
      <img 
        src={images[currentImage]} 
        alt={`${placeName} - Photo ${currentImage + 1}`}
        className="search-result-image"
        onError={handleImageError}
        loading="lazy"
      />
      {images.length > 1 && (
        <div className="image-navigation">
          {images.map((_, index) => (
            <button 
              key={index}
              className={`nav-dot ${index === currentImage ? 'active' : ''}`}
              onClick={() => setCurrentImage(index)}
            />
          ))}
        </div>
      )}
    </div>
  );
};

export default ImageGallery;
```

#### 2. Update SearchEvents.jsx Component
```javascript
// Update components/Search/SearchEvents.jsx
import ImageGallery from './ImageGallery';

// Add to event rendering
<div className="event-card">
  <ImageGallery 
    images={event.photoUrls} 
    placeName={event.name} 
  />
  <div className="event-details">
    <h3>{event.name}</h3>
    <p>{event.description}</p>
    <div className="event-rating">
      Rating: {event.rating || 'N/A'}
    </div>
  </div>
</div>
```

#### 3. Enhanced CSS Styles
```css
/* Add to SearchEvents.css */
.image-gallery {
  position: relative;
  width: 100%;
  height: 200px;
  overflow: hidden;
  border-radius: 8px;
}

.search-result-image {
  width: 100%;
  height: 100%;
  object-fit: cover;
  transition: transform 0.3s ease;
}

.search-result-image:hover {
  transform: scale(1.05);
}

.search-result-image.fallback {
  opacity: 0.7;
  filter: grayscale(20%);
}

.image-navigation {
  position: absolute;
  bottom: 10px;
  left: 50%;
  transform: translateX(-50%);
  display: flex;
  gap: 5px;
}

.nav-dot {
  width: 8px;
  height: 8px;
  border-radius: 50%;
  border: none;
  background: rgba(255, 255, 255, 0.5);
  cursor: pointer;
  transition: background 0.3s ease;
}

.nav-dot.active {
  background: rgba(255, 255, 255, 1);
}

.event-card {
  border: 1px solid #ddd;
  border-radius: 12px;
  overflow: hidden;
  box-shadow: 0 2px 8px rgba(0,0,0,0.1);
  transition: transform 0.2s ease;
}

.event-card:hover {
  transform: translateY(-2px);
  box-shadow: 0 4px 16px rgba(0,0,0,0.15);
}

/* Loading skeleton for images */
.image-loading {
  background: linear-gradient(90deg, #f0f0f0 25%, #e0e0e0 50%, #f0f0f0 75%);
  background-size: 200% 100%;
  animation: loading 1.5s infinite;
}

@keyframes loading {
  0% { background-position: 200% 0; }
  100% { background-position: -200% 0; }
}
```

#### 4. Add Fallback Images
```javascript
// public/images/default-place.jpg
// Create default placeholder images for different categories:
// - default-restaurant.jpg
// - default-attraction.jpg
// - default-hotel.jpg
// - default-activity.jpg
```

### Environment Variables
```bash
# Backend (.env) - Already exists, just ensure it's being used for photos
GOOGLE_PLACES_API_KEY=your_google_places_api_key
```

## Implementation Steps

1. **Backend Photo Integration**
   - Add Google Places Photo API calls
   - Implement image proxy middleware
   - Update search response format to include photoUrls
   - Add error handling for missing images

2. **Frontend Image Components**
   - Create ImageGallery component
   - Update SearchEvents component to display images
   - Add loading states and error handling
   - Implement image optimization and lazy loading

3. **Fallback System**
   - Add default placeholder images
   - Implement graceful degradation for missing images
   - Add image error handling with fallbacks

4. **Performance Optimization**
   - Implement image lazy loading
   - Add image compression/optimization
   - Cache frequently accessed images
   - Optimize for mobile devices

## Acceptance Criteria

- [ ] Events and places display high-quality images from Google Places
- [ ] Image carousel shows multiple photos when available
- [ ] Fallback images display when no photos are available
- [ ] Images load efficiently with lazy loading
- [ ] Image error handling works gracefully
- [ ] Mobile-responsive image display
- [ ] Images enhance user experience and engagement
- [ ] Loading states show while images are fetching
- [ ] CORS issues with images are resolved
- [ ] Performance impact is minimal

## Testing Checklist

- [ ] Search for events with images (restaurants, attractions)
- [ ] Search for events without images (verify fallbacks)
- [ ] Test image carousel navigation
- [ ] Verify mobile responsiveness
- [ ] Test slow network conditions
- [ ] Verify CORS handling for Google images
- [ ] Test error handling for broken image URLs

## Priority: P0 - Critical for user experience and visual appeal

This fix will dramatically improve the user experience by making the app visually appealing and helping users make better travel decisions based on visual information.
